-- 使用者群組（每個群組一次只能有一位管理員）
CREATE TABLE IF NOT EXISTS user_groups (
    group_id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    group_name        VARCHAR(64) NOT NULL UNIQUE,
    created_date      TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP NOT NULL
);

-- 餐廳資料
CREATE TABLE IF NOT EXISTS restaurants (
    restaurant_id    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 51) PRIMARY KEY,  -- 餐廳編號
    group_id         INT NOT NULL,                                                       -- 所屬群組
    restaurant_name  VARCHAR(64)  NOT NULL,                                              -- 餐廳名稱
    category         VARCHAR(32)  NOT NULL,                                              -- 餐廳分類
    image_url        VARCHAR(256),                                                       -- 餐廳圖片URL
    visited_count    INT DEFAULT 0,                                                      -- 選擇次數
    last_selected_at TIMESTAMP NULL DEFAULT NULL,                                        -- 最後選擇時間
    updated_at       TIMESTAMP NULL DEFAULT NULL,                                        -- 最後更新資料時間
    note             VARCHAR(512),                                                       -- 備註
    CONSTRAINT fk_restaurants_group_id FOREIGN KEY (group_id) REFERENCES user_groups(group_id)
);

-- 抽選餐廳歷史紀錄
CREATE TABLE IF NOT EXISTS restaurant_history (
    history_id       INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,   -- 歷史紀錄編號
    group_id         INT NOT NULL,                                                       -- 所屬群組
    restaurant_id    INT NOT NULL,                                                       -- 餐廳編號
    restaurant_name  VARCHAR(64) NOT NULL,                                               -- 餐廳名稱（快照）
    category         VARCHAR(32) NOT NULL,                                               -- 餐廳分類（快照）
    selected_at      TIMESTAMP NOT NULL,                                                 -- 被選中的時間
    CONSTRAINT fk_history_group_id FOREIGN KEY (group_id) REFERENCES user_groups(group_id)
);

-- 餐點資料
CREATE TABLE IF NOT EXISTS dishes (
    dish_id       INT GENERATED BY DEFAULT AS IDENTITY (START WITH 400) PRIMARY KEY,    -- 餐點編號
    restaurant_id INT NOT NULL,                                                          -- 餐點對應餐廳編號
    price         INT NOT NULL,                                                          -- 餐點價格
    dish_name     VARCHAR(32) NOT NULL                                                   -- 餐點名稱
);

-- 帳號資料
CREATE TABLE IF NOT EXISTS users
(
    user_id            INT GENERATED BY DEFAULT AS IDENTITY (START WITH 30) PRIMARY KEY, -- 使用者 ID
    group_id           INT NOT NULL,                                                      -- 所屬群組
    username           VARCHAR(256) NOT NULL UNIQUE,                                      -- 使用者帳號
    user_password      VARCHAR(256) NOT NULL,                                             -- 使用者密碼
    roles              VARCHAR(32),                                                       -- 使用者角色
    created_date       TIMESTAMP NOT NULL,                                                -- 建立時間
    last_modified_date TIMESTAMP NOT NULL,                                                -- 最後修改時間
    CONSTRAINT fk_users_group_id FOREIGN KEY (group_id) REFERENCES user_groups(group_id)
);